/**
 * Created by shenzp on 18/12/17.
 */


var ResultCode = {
    BASE_CODE: 10000
};
var RC = ResultCode;

// DB
RC.CODE_DB_MYSQL_ERROR = RC.BASE_CODE + 9999;
RC.CODE_DB_ES_ERROR = RC.BASE_CODE + 9998;

// login
RC.CODE_LOGIN_BASE = RC.BASE_CODE + 500;
RC.CODE_CAPTCHA_VERIFY_BASE = RC.CODE_LOGIN_BASE + 1;
RC.CODE_CAPTCHA_VERIFY_PARAMETER_ERROR = RC.CODE_LOGIN_BASE + 2;
RC.CODE_CAPTCHA_VERIFY_WRONG = RC.CODE_LOGIN_BASE + 3;
RC.CODE_CAPTCHA_VERIFY_OVERDUE = RC.CODE_LOGIN_BASE + 4;
RC.CODE_LOGIN_MISS_CAPTCHA_ID = RC.CODE_LOGIN_BASE + 5;
RC.CODE_LOGIN_MISS_PHONE = RC.CODE_LOGIN_BASE + 6;
RC.CODE_LOGIN_MISS_PASSWORD = RC.CODE_LOGIN_BASE + 7;
RC.CODE_LOGIN_MISS_CAPTCHA = RC.CODE_LOGIN_BASE + 8;
RC.CODE_LOGIN_PHONE_PASSWORD_ERROR = RC.CODE_LOGIN_BASE + 9;
// Logout
RC.CODE_LOGOUT_BASE = RC.CODE_LOGIN_BASE + 10;


export default ResultCode;
